language: generic
sudo: false
services:
  - docker
before_script:
  - cp config/database.yml.travis config/database.yml
install:
  - docker run -d --name=postgres postgres:9.6
script:
  - docker run --link postgres:postgres --volume=$TRAVIS_BUILD_DIR:/app -it leelongmore/cgsd-api-rails-ci /bin/sh -c "bundle --without development production && bundle exec rake db:test:prepare && bundle exec rspec spec"

