default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: cgsd_publish_development

test:
  <<: *default
  database: cgsd_publish_test
